from .client import JapydClient
from .dotnet import JsonApiBaseModel, JsonApiQueryModel
from .jsonapi import (
    Error,
    JsonApiApp,
    JsonApiBodyModel,
    Link,
    MultiBodyModel,
    MultiResourcesTopLevel,
    Relationship,
    Resource,
    ResourceIdentifier,
    SingleBodyModel,
    SingleResourceTopLevel,
    TopLevel,
    extract_from_resource_identifier,
    extract_relationship,
    flatten_resource,
)

__all__ = [
    "Error",
    "JapydClient",
    "JsonApiApp",
    "JsonApiBaseModel",
    "JsonApiBodyModel",
    "JsonApiQueryModel",
    "Link",
    "MultiBodyModel",
    "MultiResourcesTopLevel",
    "Relationship",
    "Resource",
    "ResourceIdentifier",
    "SingleBodyModel",
    "SingleResourceTopLevel",
    "TopLevel",
    "extract_from_resource_identifier",
    "extract_relationship",
    "flatten_resource",
]
