name: PyPi

on:
  push:
    branches: [ "main" ]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-tags: true

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12

      - name: Trace referecne
        run: echo ${GITHUB_REF}

      - name: Check version change
        id: version_check
        run: |
          LAST_VERSION=$(git describe --tags --abbrev=0)
          CURRENT_VERSION=$(pdm show --version)
          if [ "$LAST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to PyPI
        run: pdm publish
        if: github.event_name == 'push' && steps.version_check.outputs.version_changed == 'true'
