name: PyPi

on:
  push:
    branches: [ "main" ]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12

      - name: Trace referecne
        run: echo ${GITHUB_REF}

      - name: Publish package distributions to PyPI
        run: pdm publish
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        if: github.event_name == 'push'
